"""
Django settings for othello project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

"""
Every comment with DEVEL should be checked before running a development server
"""

import os
try:
    from .ion_secret import *
except ImportError:
    pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_ROOT = BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = ""
# SECURITY WARNING: don't run with debug turned on in production!
# DEVEL: change this to true
DEBUG = True

# DEVEL: change this if necessary
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "127.0.0.3", "othello.tjhsst.edu"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'social_django',
    'channels',

    'othello',
    'othello.apps.auth',
    'othello.apps.users',
    'othello.apps.games',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'othello.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(PROJECT_ROOT, 'django.log'),
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'othello': {
            'handlers': ['console', 'file'],
            # DEVEL: might want to set this to 'DEBUG' sometimes
            'level': 'INFO',
            'propagate': True,
        },
    },
}

WSGI_APPLICATION = 'othello.wsgi.application'
ASGI_APPLICATION = 'othello.routing.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [("localhost", 6379)],
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'othello.apps.auth.oauth.IonOauth2',
]

# DEVEL: set this to False
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

AUTH_USER_MODEL = "users.User"

SOCIAL_AUTH_USER_FIELDS = ['username', 'full_name', 'email', 'id', 'is_superuser', 'is_staff']

SOCIAL_AUTH_URL_NAMESPACE = 'social'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/upload'
LOGIN_ERROR_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'othello/static/')
#MEDIA_URL = "/code/"
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'students')

OTHELLO_ROOM_ID_LEN = 32
OTHELLO_AI_UNKNOWN_PLAYER = "Unknown"
OTHELLO_AI_HUMAN_PLAYER = "Yourself"
OTHELLO_AI_UNLIMITED_PLAYER = "alphazero"
OTHELLO_AI_SHARED_DIR = os.path.join(MEDIA_ROOT, "public")
# DEVEL: set this to "python -u {2} =NAME=".format(...)
OTHELLO_AI_RUN_COMMAND = "firejail --quiet --profile={0} --whitelist={1} python3 -u {2} =NAME=".format(
    os.path.join(PROJECT_ROOT, "python-custom.profile"),
    os.path.join(PROJECT_ROOT, "students/=NAME="),
    os.path.join(PROJECT_ROOT, "run_ai_jailed.py")
)
OTHELLO_AI_NAME_REPLACE = "=NAME="
