# Generated by Django 2.0.2 on 2018-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('black', models.CharField(max_length=64, null=True)),
                ('white', models.CharField(max_length=64, null=True)),
                ('timelimit', models.FloatField(null=True)),
            ],
        ),
    ]
