# Generated by Django 2.0.2 on 2018-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='black',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='timelimit',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='white',
            field=models.CharField(default='Unknown', max_length=64),
        ),
    ]
