# Generated by Django 2.0.2 on 2018-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180302_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='playing',
            field=models.BooleanField(default=False),
        ),
    ]
