# Generated by Django 3.0.1 on 2020-01-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_room_playing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
